// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/CustomCard/ArticleCard.vue')['default']
    ArticleListCard: typeof import('./src/components/CustomCard/ArticleListCard.vue')['default']
    BarTitle: typeof import('./src/components/CustomTitle/BarTitle.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    CustomCard: typeof import('./src/components/CustomCard/index.vue')['default']
    CustomInfoBox: typeof import('./src/components/CustomInfoBox.vue')['default']
    CustomParagraph: typeof import('./src/components/CustomParagraph/index.vue')['default']
    CustomTitle: typeof import('./src/components/CustomTitle/index.vue')['default']
    EditorPassWord: typeof import('./src/components/EditorPassWord/index.vue')['default']
    EditPassword: typeof import('./src/components/EditorPassWord/EditPassword.vue')['default']
    Emoji: typeof import('./src/components/Emoji/index.vue')['default']
    Emputy: typeof import('./src/components/emputy/index.vue')['default']
    LayerBox: typeof import('./src/components/LayerBox.vue')['default']
    Metas: typeof import('./src/components/Metas/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sticky: typeof import('./src/components/Sticky/index.vue')['default']
    TimeLine: typeof import('./src/components/TimeLine/index.vue')['default']
    TimeLineItem: typeof import('./src/components/TimeLine/components/TimeLineItem.vue')['default']
    UploadAvatar: typeof import('./src/components/UploadAvatar/index.vue')['default']
  }
}

export {}
