// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '$alert': typeof import('element-plus')['ElMessageBox']['alert']
    '$confirm': typeof import('element-plus')['ElMessageBox']['confirm']
    '$loading': typeof import('element-plus')['ElLoadingService']
    '$message': typeof import('element-plus')['ElMessage']
    '$messageBox': typeof import('element-plus')['ElMessageBox']
    '$msgbox': typeof import('element-plus')['ElMessageBox']
    '$notify': typeof import('element-plus')['ElNotification']
    '$prompt': typeof import('element-plus')['ElMessageBox']['prompt']
    CustomInfoBox: typeof import('./src/components/CustomInfoBox.vue')['default']
    CustomTitle: typeof import('./src/components/CustomTitle.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTree: typeof import('element-plus/es')['ElTree']['default']
    Emoji: typeof import('./src/components/Emoji/index.vue')['default']
    LayerBox: typeof import('./src/components/LayerBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SVGComponents: typeof import('./src/components/SVGComponents/index.vue')['default']
    UploadAvatar: typeof import('./src/components/UploadAvatar/index.vue')['default']
  }
}

export {}
